// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuo8yXepvqSgucdLKgIFHSpHKTl1Xaaw8',
    appId: '1:962830519173:web:17259c92bb82bd20d192ec',
    messagingSenderId: '962830519173',
    projectId: 'student-app-ee7de',
    authDomain: 'student-app-ee7de.firebaseapp.com',
    storageBucket: 'student-app-ee7de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubq4lPdSKgtblEiqoT4sF0etCb_n4RP4',
    appId: '1:962830519173:android:53415d83963222bcd192ec',
    messagingSenderId: '962830519173',
    projectId: 'student-app-ee7de',
    storageBucket: 'student-app-ee7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KCSowP_FKPC78QNZF9cjyB6MMca8FII',
    appId: '1:962830519173:ios:d80ea792f581a6b0d192ec',
    messagingSenderId: '962830519173',
    projectId: 'student-app-ee7de',
    storageBucket: 'student-app-ee7de.firebasestorage.app',
    iosBundleId: 'com.example.studentSystemv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KCSowP_FKPC78QNZF9cjyB6MMca8FII',
    appId: '1:962830519173:ios:d80ea792f581a6b0d192ec',
    messagingSenderId: '962830519173',
    projectId: 'student-app-ee7de',
    storageBucket: 'student-app-ee7de.firebasestorage.app',
    iosBundleId: 'com.example.studentSystemv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuo8yXepvqSgucdLKgIFHSpHKTl1Xaaw8',
    appId: '1:962830519173:web:44ef28e3fd63978cd192ec',
    messagingSenderId: '962830519173',
    projectId: 'student-app-ee7de',
    authDomain: 'student-app-ee7de.firebaseapp.com',
    storageBucket: 'student-app-ee7de.firebasestorage.app',
  );

}